version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node

    steps:
      - checkout

      - run:
          name: Ruby dependencies
          command: bundle install

      - run:
          name: Node dependencies
          command: sudo npm install -g firebase-tools@4.0.2 --unsafe-perm

      - run:
          name: Build
          command: bundle exec jekyll build --verbose

      - run:
          name: Deploy
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
